/* ===========================================================
   Umain AI Jam — SHARED NAV.  DO NOT EDIT THIS FILE.
   Injects the nav into <div id="umain-nav"></div> on every page
   and highlights the active link by filename. Edit only your page.
   =========================================================== */
(function () {
  var logo = '<svg width="73" height="13" viewBox="0 0 73 13" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Umain"><path d="M32.0206 12.6304L35.4367 0H41.5479L44.964 12.6304H41.5479L40.9211 10.1059H36.0635L35.4367 12.6304H32.0206ZM36.7843 7.21964H40.2003L39.1191 3.06717H38.4218H37.8655L36.7843 7.21964Z" fill="#111111"/><path d="M0 7.5892V0.00779724H3.32985V7.49483C3.32985 8.24982 3.5414 8.84753 3.95665 9.28008C4.3719 9.71263 4.94385 9.93283 5.66467 9.93283C6.38548 9.93283 6.9496 9.71263 7.37268 9.28008C7.78794 8.84753 7.99948 8.24982 7.99948 7.49483V0.00779724H11.3293V7.5892C11.3293 9.22503 10.8201 10.5384 9.80152 11.5215C8.78298 12.5045 7.40403 13 5.66467 13C3.92531 13 2.54636 12.5045 1.52781 11.5215C0.509272 10.5384 0 9.22503 0 7.5892Z" fill="#111111"/><path d="M14.6116 12.6382V0.00779724H19.289L22.1096 6.98363L24.9537 0.00779724H29.6312V12.6382H26.3013L26.3953 3.7985L23.9665 10.098H20.2841L17.8787 3.7985L17.9493 12.6382H14.6116Z" fill="#111111"/><path d="M47.3465 12.6382V0.00779724H50.6685V12.6382H47.3465Z" fill="#111111"/><path d="M53.9578 12.6382V0.00779724H58.0006L62.4038 7.95097L62.3098 0.00779724H65.6318V12.6382H61.589L57.1936 4.70292L57.2876 12.6461H53.9578V12.6382Z" fill="#111111"/><path d="M72.2216 0.00779724H68.9309V3.3109H72.2216V0.00779724Z" fill="#111111"/></svg>';

  var items = [
    ["index.html", "Home"],
    ["about.html", "About Us"],
    ["team.html", "Product Design Team"],
    ["contact.html", "Contact"],
    ["404.html", "404"]
  ];

  var file = (location.pathname.split("/").pop() || "index.html");
  if (file === "") file = "index.html";

  var links = items.map(function (it) {
    var active = it[0] === file ? ' class="active"' : "";
    return '<a href="' + it[0] + '"' + active + ">" + it[1] + "</a>";
  }).join("");

  var html =
    '<a class="um-brand" href="index.html" aria-label="Umain">' + logo + "</a>" +
    '<button class="um-burger" type="button" aria-label="Menu" aria-expanded="false">Menu <b>&#9776;</b></button>' +
    '<div class="um-pill">' + links + "</div>" +
    '<span class="um-eidra">Part of Eidra</span>';

  var mount = document.getElementById("umain-nav");
  if (!mount) {
    mount = document.createElement("div");
    document.body.insertBefore(mount, document.body.firstChild);
  }
  mount.className = "um-topbar";
  mount.innerHTML = html;

  var btn = mount.querySelector(".um-burger");
  btn.addEventListener("click", function () {
    var open = mount.classList.toggle("um-open");
    btn.setAttribute("aria-expanded", open);
  });
})();
